name: Pipeline

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Debug, Release]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install conan
        uses: turtlebrowser/get-conan@v1.2
        with:
          version: 1.59.0

      - name: Configure CMake
        if: matrix.os != 'ubuntu-latest'
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_TEST=1

      - name: Configure CMake
        if: matrix.os == 'ubuntu-latest'
        run: |
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DBUILD_TEST=1 -DBUILD_ITEST=1

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{ matrix.build-type }}

      - name: Test
        if: matrix.os != 'ubuntu-latest'
        run: |
          ctest --output-on-failure --stop-on-failure --test-dir ${{github.workspace}}/build -C ${{ matrix.build-type }}

      - name: Test
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker run -p 6379:6379 -d redis
          ctest --output-on-failure --stop-on-failure --test-dir ${{github.workspace}}/build -C ${{ matrix.build-type }}

  # coverage:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Install conan
  #       uses: turtlebrowser/get-conan@v1.2
  #       with:
  #         version: 1.59.0

  #     - name: Install lcov
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install lcov

  #     - name: Configure CMake
  #       run: |
  #         cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Debug -DBUILD_TEST=1 -DBUILD_COVERAGE=1

  #     - name: Calculate coverage
  #       run: |
  #         cmake --build ${{github.workspace}}/build --target coverage

  #     - name: Upload coverage
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: coverage
  #         path: ${{github.workspace}}/coverage
